spring.application.name=spring-ai
logging.pattern.console=%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n
#spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.google.genai.api-key=${GOOGLE_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-3.6-flash
spring.ai.google.genai.embedding.api-key=${GOOGLE_API_KEY}
spring.ai.google.genai.embedding.text.model=gemini-embedding-001
logging.level.org.springframework.ai.chat.client.advisor=DEBUG

spring.datasource.url=jdbc:h2:file:~/chatmemory;AUTO_SERVER=true
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=madan
spring.datasource.password=12345
spring.h2.console.enabled=true

#spring.ai.openai.embedding.model=text-embedding-3-small

spring.ai.chat.memory.repository.jdbc.initialize-schema=always
spring.docker.compose.file=section05/springai/compose.yml
spring.docker.compose.stop.command=down

spring.ai.vectorstore.qdrant.initialize-schema=true
spring.ai.vectorstore.qdrant.host=localhost
spring.ai.vectorstore.qdrant.port=6334
spring.ai.vectorstore.qdrant.collection-name=eazybytes